### ISSUE TITLE
Bug: ocktokit request to [URI]/tags/protection is depreciated

### ISSUE THREAD

**Issue by mattpu-sportsbet** [timrogers/gh-migration-audit#190]
Running the latest version of the tool against our org is spitting an error as follows:
`[@octokit/request] "GET https://api.github.com/repos/[ORG]/[REPO]/tags/protection" is deprecated. It is scheduled to be removed on Fri, 30 Aug 2024 07:00:00 GMT. See https://gh.io/tag-protection-sunset`

**Comment by timrogers** [comment]
Yep - I can see this too 👀  It makes sense that Octokit.js logs for this kind of thing - but it doesn't look like there is a way we can turn it off. Maybe we can just add a log in this project to say "don't worry about it"?

**Comment by timrogers** [comment]
This log is now suppressed, so not more noisy logs 📣 : https://github.com/timrogers/gh-migration-audit/pull/198

On August 30, 2024, I will update this tool so the tag protection rules auditor doesn't run at all on GitHub.com: https://github.com/timrogers/gh-migration-audit/issues/199
